#=============================================================================
# Serveur DNS -- Admin. Sys. 2017 -- NOEL, LAGACHE, DELANDER
#=============================================================================

FROM sameersbn/bind:latest

# A AJOUTER MES CONFIGS
